[package]
name = 'SharedStakePool'
version = '0.2.0'

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
openrails = '0x39ce2ae8d65ceb28cd8688ea78dafdf2177fd7a574e535035ad2f2feacb9998d'
test_user = '0x333'
# openrails = "0x013f0ec8bddb23df2804aa24ff2b807ec937e29f75e25f17cb12a52fb91e921a"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'testnet'

[dependencies.AptosStdlib]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-stdlib'
rev = 'testnet'

[dependencies.MoveStdlib]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/move-stdlib'
rev = 'testnet'
